# PCA

In [1]:
import numpy as np
import numpy.linalg as LA
np.set_printoptions(suppress=True)

X = np.array([[1, 0, 1, 0], [1, 0, 1, 0], [1, 0, 1, 0]])
X_prime = np.array([[1, 0, 0, 1], [1, 0, 0, 1], [1, 0, 0, 1]])
d = 1

print(X @ X.T)

w, v = LA.eig(X @ X.T)
v = v.T # The eigenvalues returned by linalg.eig are columns vectors by default
print(f"Eigval (XX^T): {w}\nEigvectors (XX^T): {v}")

[[2 2 2]
 [2 2 2]
 [2 2 2]]
Eigval (XX^T): [ 6.  0. -0.]
Eigvectors (XX^T): [[ 0.57735027  0.57735027  0.57735027]
 [-0.         -0.70710678  0.70710678]
 [ 0.60978166 -0.77512986  0.1653482 ]]


In [2]:
from sklearn.decomposition import PCA
pca = PCA(n_components=d)
pca.fit(X)
print(pca.components_)
print(pca.explained_variance_)

[[1. 0. 0. 0.]]
[0.]


/home/mike/.local/lib/python3.8/site-packages/sklearn/decomposition/_pca.py:501: RuntimeWarning: invalid value encountered in true_divide
  explained_variance_ratio_ = explained_variance_ / total_var
